### ISSUE TITLE
Seeing all records when using a DirectStore

### ISSUE THREAD

**Issue by dilipramji** [aghuddleston/Ext.ux.data.PagingStore#1]
Hi,

I'm using ExtJS 4.2.1 and am trying to use your port of the PagingStore with a DirectProxy where autoLoad is false because the user has to populate query fields and click a search button to populate the store. Clicking the button calls store.load() with the start, limit, page, and params values sent but the grid still loads all the records even though the paging toolbar is showing correct paging information. The server is sending back all the records because the query takes a long time to run so I want paging to be done locally to minimize the server hits. Is there a special way to load the store such that only the first slice of records is viewable in page one? I tried calling "applyPaging()" right after "load()" but this causes the grid to now truncate the records into that single slice with no ability to move to a next page. For example if my pageSize is 30 and I get 43 records back, the call to applyPaging() causes the toolbar to display "1 to 30 of 30" instead of "1 to 30 of 43".

Thanks,

Dilip

**Comment by aghuddleston** [comment]
First, I should clarify that I haven't tried this with 4.2.1, since I'm still on 4.1.1.  But that said, I am using it with an AjaxProxy with autoLoad set to false, and my paging toolbar and grid are behaving correctly.

Here is what my store looks like:

```
Ext.define('My.store.Users', {
    extend: 'Ext.ux.data.PagingStore',
    alias: 'store.users',
    model: 'My.model.User',
    autoLoad: false,
    pageSize: 50,
    lastOptions: {
        start: 0,
        limit: 50,
        page: 1
    },

    proxy: {
        type: 'ajax',
        url: 'put/url/here',
        reader: {
            type: 'json',
            root: 'rows',
            totalProperty: 'total',
            successProperty: 'success',
            messageProperty: 'message'
        },
        actionMethods: {
            create: 'POST',
            read: 'POST',
            update: 'POST',
            destroy: 'POST'
        },
        limitParam: undefined,
        pageParam: undefined,
        startParam: undefined
    }
});
```

And in my contoller, I call the store like so:

```
    onFind: function () {
        var grid = this.getMyGrid(),
            searchPanel = this.getSearchPanel(),
            myStore = this.getMyStore(),
            params;

        params = searchPanel.getValues();

        delete myStore.lastParams;
        myStore.proxy.extraParams = params;
        myStore.load({
            start:0,
            limit:50,
            page:1,
            scope: this,
            callback: this.findCallback
        });
    },

```

The findCallback just has error handling, nothing paging related.  

Let me know if this helps.

**Comment by dilipramji** [comment]
Thanks for your response. Is your server returning all records, or just the
page slice of records?

**Comment by aghuddleston** [comment]
All records.

**Comment by dilipramji** [comment]
I'm still not having much luck here. Could I see how your grid and paging
toolbar are defined and using the store?

**Comment by aghuddleston** [comment]
There's nothing unusual about them..  The grid is referencing the store, in my real code named 'Users', that "standard   MVC" way.  In initComponent on my grid I have

```
me.store = 'Users'
```

And for my paging toolbar I have this config:

```
            {
                xtype: 'pagingtoolbar',
                itemId: 'pagingBar',
                dock: 'top',
                displayInfo: true,
                displayMsg: 'Displaying users {0} - {1} of {2}',
                emptyMsg: 'No users to display',
                pageSize: 50,
                alignPagingRight: true,
                prependButtons: true,
                items : [
                    {
                        text : 'Email',
                        itemId: 'emailButton',
                        tooltip : 'Email Selected Users',
                        iconCls : 'icon-email',
                        disabled : true
                    }
                ],
                store: 'Users'
            }
```

It's possible a framework change between 4.1.1 and 4.2.1 makes the current version of this plugin not work.  I haven't used 4.2.1 at all, so I really have no idea.  Don't forget, you can always step into the code...

**Comment by dilipramji** [comment]
OK, I think I figured out what was going wrong. I had Ext.ux.grid.FiltersFeature setup on the grid and when stepping through the code, it seems like FiltersFeature holds a reference to the store that is not paged, so during the grid view refresh phase, this copy of the store overwrites the paged version. I followed the method outlined in the following post and it seems like it's now working with your PagingStore and FiltersFeature:

http://www.sencha.com/forum/showthread.php?71532-Ext.ux.data.PagingStore-v0.5&p=765222&viewfull=1#post765222

Thanks for your help!

**Comment by dilipramji** [comment]
Just wondering if this happens for you too: the first time I click on the "nextPage" button, the grid spends a little time loading before showing the records. After that when I click the "nextPage" button, the records appear instantly. I've been trying to step through to see what causes the hold up for that first click, but the debugger starts stepping through blank lines so I'm not sure I'm seeing the actual code being stepped through.

**Comment by aghuddleston** [comment]
I just clicked through my paged grid and I'm not seeing that, but I'll keep an eye on it.  Let me know if you find something.
