### ISSUE TITLE
Clearing data issue

### ISSUE THREAD

**Issue by dilipramji** [aghuddleston/Ext.ux.data.PagingStore#2]
Hi again,

I noticed a problem where the store "data" property was not being cleared during the call to removeAll(). I traced the issue to the applyPaging() method where we overwrite the store's "data" property with values from the "allData" property. The "generation" property is not copied over and causes the store not to clear the data because it uses the "generation" value to determine whether there was any data to clear. Adding a line to copy this over fixed my problem.

Have you run into this situation? The "generation" property was added in 4.1.0 according to the docs.

Thanks,

Dilip

**Comment by aghuddleston** [comment]
I see that generation and pageMaps are used for buffered stores.  I have to admit that I did not try to get the paging store to work with buffered stores.  I probably thought the use cases for the paging store and buffered stores did not coincide.  This does not seem true in your case.  If you are using this extension with buffered stores, you'll probably want to do some testing to make sure it is working for all cases.  Feel free to fork the repository and submit a pull request.
